It works! woho0o!!
now fs2ram gets neutralized and purged correctly.

A reboot is required because I'm not going to kill processes at random so I can unmount the damn folders.

will update plugin description shortly after this

diff --git a/usr/share/openmediavault/mkconf/flashmemory b/usr/share/openmediavault/mkconf/flashmemory
--- a/usr/share/openmediavault/mkconf/flashmemory
+++ b/usr/share/openmediavault/mkconf/flashmemory
@@ -35,7 +35,7 @@ fi
 # https://www.debian-administration.org/article/661/A_transient_/var/log 
 
 # create folder2ram config
-cat > ${FOLDER2RAM_CONFIG} <<'EOF' 
+cat > ${FOLDER2RAM_CONFIG} <<'EOF'
 #############################
 #folder2ram main config file#
 #############################
@@ -60,6 +60,7 @@ tmpfs           /var/lib/monit
 #this file was automatically generated by openmediavault-flashmemory plugin
 EOF
 
+
 #sending a housekeeping script to /tmp so that we do the following modifications in a moment that won't upset apt-get
 cat > ${HOUSEKEEPER} <<'EOF'
 #!/bin/bash
@@ -68,37 +69,32 @@ cat > ${HOUSEKEEPER} <<'EOF'
     sleep 1
     done
 #disabling apt disk cache so its folder in /var/cache/apt/whatever will stop filling up. Also saves additional writes.
-    echo Dir::Cache ""; > /etc/apt/apt.conf.d/02nocache 
-    echo Dir::Cache::archives ""; >> /etc/apt/apt.conf.d/02nocache
+    echo "Dir::Cache "";" > /etc/apt/apt.conf.d/02nocache 
+    echo "Dir::Cache::archives "";" >> /etc/apt/apt.conf.d/02nocache
 #disabling cron-apt package download by erasing the file asking for it.
-    rm /etc/cron-apt/action.d/3-download
+    rm -f /etc/cron-apt/action.d/3-download
 #deleting the packages already in the cache, because otherwise this is all wasted space in the tmpfs 
-#and time wasted on startup and shutdown as all this stuff is compressed/extracted, especially for devices with weak processors
-    rm /var/cache/apt/archives/*
-    rm /var/cache/apt/archives/partial/*
-    
-#checking if fs2ram has been shut down by setup scripts
-    while [[ ! -e /run/lock/fs2ramdisabled ]]; do
-    sleep 1
-    done
-#removing fs2ram
-    apt-get -y purge fs2ram
+#and time wasted on startup and shutdown 
+    rm -fr /var/cache/apt/archives/*
+    mkdir -p /var/cache/apt/archives/partial
 #script self-destruct, deletes this script from disk. technically optional, as /tmp content gets dumped anyway on startup.
-    rm /tmp/folder2ramhousekeeper
+    rm -f /tmp/folder2ramhousekeeper
 exit 0
 EOF
+
 
 #making it executable
 chmod +x ${HOUSEKEEPER}
 
 #calling it up as another process, so this script can quit and installation of whatever else can continue.
-bash ${HOUSEKEEPER}
+nohup ${HOUSEKEEPER} &
 
 
 #now we need to put fs2ram to sleep safely if it is still online
 
 
-#checking if fs2ram is still there, if it isn't found the script ends here
+
+#checking if fs2ram is online
 if [ ! -f /sbin/fs2ram ]; then
 exit 0;
 fi
@@ -110,14 +106,14 @@ read_fs2ram_mount_points() {
 # $line_number must come from outside
 # blank lines and commented lines are ignored, so line_number refers only to actual mount points
 
-line_number=$1 
+line_number=$1
 
 # remove blank and commented lines with sed, select only lines that have "keep_file_content" option,
 # get variable form outside in awk, and use it to print line at $line_number
-mount_point=$( sed '/^[[:space:]]*$/d' /etc/fs2ram/fs2ram.conf | sed '/^#/d' | sed -n '/keep_file_content/p' | awk -v line="$line_number" 'NR == line {print $2}' )
+mount_point=$( sed '/^[[:space:]]*$/d' /etc/fs2ram/fs2ram.conf | sed '/^#/d' | awk -v line="$line_number" 'NR == line {print $2}' )
 
 # checking if mount point variable is empty, and if it is returning a keyword
-if [ "x$mount_point" != "x" ]; then 
+if [ "x$mount_point" != "x" ]; then
 echo "$mount_point";
 else
 echo "no_more_mount_points";
@@ -130,9 +126,9 @@ fi
 #moving files to temp folders so we can shut down fs2ram safely
 
 # initializing variables    
-line_number=1 
+line_number=1
 
-echo "moving all tmpfs data to temp folders on system drive so we can get it back when fs2ram is powered down"
+#echo "moving all tmpfs data to temp folders on system drive so we can get it back when fs2ram is powered down"
 
 ######################CHECKING IF THERE ARE STILL MOUNT POINTS
 
@@ -146,15 +142,15 @@ mount_point=$(read_fs2ram_mount_points "$line_number")
 until [ "$mount_point" = "no_more_mount_points" ] ;  do
 
 # calling another function (above) to fill DIR, a directory variable at this line number
-DIR=$(read_fs2ram_mount_points "$line_number")
+DIR=$mount_point
 
 ################FUNCTION PAYLOAD#############
 
 #this is the path of the temporary folders where we store things while powering down fs2ram
-DIRPERM="/var/folder2ram/temp$DIR"
+DIRPERM="/var/folder2ram/temporary$DIR"
 
 #making folder if not existing
-[ -d "$DIRPERM" ] || mkdir -p "$DIRPERM"
+mkdir -p "$DIRPERM"
 
 #copy the contents of original folder in a temporary folder
 cp -rfp "$DIR" -T "$DIRPERM"
@@ -177,20 +173,77 @@ done
 
 ############DEACTIVATING FS2RAM
 
-# shuttins down fs2ram on all tmpfs
-fs2ram unmount -a -f
+#Hijacking the fs2ram initscript to do the cleaning and reloading
+# three birds with one stone, we need a initscript, we need fs2ram to not start again
+# and we need something that gets cleaned afterwards
 
-#if it fails horribly it can be changed with yet another while cycle like the above, 
-#reading and and unmounting manually all mount points of fs2ram 
-#config file. I hope it won't be necessary.
+fs2ram_init="/etc/init.d/fs2ram"
 
-######################################
+rm -f "$fs2ram_init"
+touch "$fs2ram_init"
 
-############COPYING DATA BACK TO ORIGINAL FOLDERS:::::::::::::::
+fs2ram_remover="/etc/init.d/fs2ram-remover"
+
+cat > "$fs2ram_remover" <<'EOF'
+#! /bin/sh
+
+### BEGIN INIT INFO
+# Provides:          fs2ram-remover
+# Required-Start:    mountall
+# Required-Stop:     umountfs
+# X-Start-Before:    mountall-bootclean
+# X-Stop-After:      rsyslog syslog-ng umountnfs
+# Default-Start:     S
+# Default-Stop:      0 6
+# Short-Description: remove fs2ram.
+# Description:       removiing fs2ram safely and reloading folders
+### END INIT INFO
+. /lib/lsb/init-functions
+
+PATH=/sbin:/bin
+NAME=fs2ram-remover
+DESC=fs2ram-remover
+
+set -e
+
+case "$1" in
+    start)
+
+#checking if fs2ram is online, if it isn't, this initscript self-destructs
+if [ ! -f /sbin/fs2ram ]; then
+	insserv -r "fs2ram-remover";
+	rm -f "/etc/init.d/fs2ram-remover";
+fi
+
+
+#################### UTILITY FUNCTIONS
+
+read_fs2ram_mount_points() {
+# this reads config file at a predetemined line and extracts mount point 
+# $line_number must come from outside
+# blank lines and commented lines are ignored, so line_number refers only to actual mount points
+
+line_number=$1
+
+# remove blank and commented lines with sed,
+# get variable form outside in awk, and use it to print line at $line_number
+mount_point=$( sed '/^[[:space:]]*$/d' /etc/fs2ram/fs2ram.conf | sed '/^#/d' | awk -v line="$line_number" 'NR == line {print $2}' )
+
+# checking if mount point variable is empty, and if it is returning a keyword
+if [ "x$mount_point" != "x" ]; then
+echo "$mount_point";
+else
+echo "no_more_mount_points";
+fi
+
+}
+
+########################## START OF SCRIPT ################################
+#####getting data back
 
 echo "copying the data back to original folders in permanent storage"
 
-# initializing variables    
+# initializing variables
 line_number=1
 
 ######################CHECKING IF THERE ARE STILL MOUNT POINTS
@@ -204,18 +257,15 @@ mount_point=$(read_fs2ram_mount_points "$line_number")
 
 until [ "$mount_point" = "no_more_mount_points" ] ;  do
 
-# calling another function (above) to fill the mount point at this line number
-mount_point=$(read_fs2ram_mount_points "$line_number")
+# filling DIR and DIRPERM at this line number
+DIR="$mount_point"
+DIRPERM="/var/folder2ram/temporary$DIR"
+
 
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-
-	# DIRPERM either does not exist or is empty?
-	# making it anyway.
-	# 
-	[ -d "$DIRPERM" ] || mkdir -p "$DIRPERM" || return 2
 
 	# If DIR does not exist?
 	[ -d "$DIR" ] || return 2
@@ -225,11 +275,12 @@ mount_point=$(read_fs2ram_mount_points "$line_number")
 		# move the data from temp folder to true folder in drive
 		if cp -rfp "$DIRPERM" -T "$DIR"; then
 			# Success!
-			echo "$DIR synced"
+			rm -fr "$DIRPERM";
 		fi
 
 	fi
-	
+
+
 # increasing line number
 line_number=$((line_number+1))
 
@@ -240,15 +291,36 @@ mount_point=$(read_fs2ram_mount_points "$line_number")
 
 ########################################################
 
-##########ENDING OF MAIN LOOP:::::::::::::::::::::::::::::
+#############END OF UNTIL LOOP:::::::::::::::::
 done
 
-########################MAKING SURE FS2RAM STAYS DOWN
-# commenting out fs2ram config file so it will not come back
-sed -i "" "s/^\([^#]\)/#\1/g" /etc/fs2ram/fs2ram.conf
+#removing fs2ram
+/usr/bin/dpkg -P fs2ram
 
-#############SIGNALING READY TO HOUSEKEEPER
-touch /run/lock/fs2ramdisabled
+exit
+        ;;
+    stop|restart|force-reload)
+        # You probably don't want to do that before closing all the files opened on the concerned mountpoints
+        echo "Error: argument '$1' not supported." >&2
+        exit 3
+        ;;
+    *)
+        N=/etc/init.d/$NAME
+        echo "Usage: $N [start]" >&2
+        exit 3
+        ;;
+esac
 
+exit 0
+
+EOF
+
+#making it executable
+chmod +x "$fs2ram_remover"
+
+#updating initscripts
+insserv "$fs2ram_remover"
+
+reboot
 
 exit 0
