added code to put fs2ram to sleep
will check if the fs2ram main script is still there, 
then sync all fs2ram mounted folders to a temp folder on disk, 
then shut down fs2ram, 
then sync the contents from the temp folder to the actual folder on disk now that it is accessible,
then comment out all lines in fs2ram config (so on reboot it won't start anything).
then leave a signal for the housekeeper script above that fs2ram can be removed.

Should work, not tested yet though.

diff --git a/usr/share/openmediavault/mkconf/flashmemory b/usr/share/openmediavault/mkconf/flashmemory
--- a/usr/share/openmediavault/mkconf/flashmemory
+++ b/usr/share/openmediavault/mkconf/flashmemory
@@ -64,7 +64,7 @@ EOF
 cat <<'EOF' > ${HOUSEKEEPER}
 #!/bin/bash
 #waiting for the package manager to finish its job.
-    while [[ ! -f /var/lib/dpkg/lock ]]; do
+    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
     sleep 1
     done
 #disabling apt disk cache so its folder in /var/cache/apt/whatever will stop filling up. Also saves additional writes.
@@ -76,6 +76,13 @@ cat <<'EOF' > ${HOUSEKEEPER}
 #and time wasted on startup and shutdown as all this stuff is compressed/extracted, especially for devices with weak processors
     rm /var/cache/apt/archives/*
     rm /var/cache/apt/archives/partial/*
+    
+#checking if fs2ram has been shut down by setup scripts
+    while [[ ! -e /run/lock/fs2ramdisabled ]]; do
+    sleep 1
+    done
+#removing fs2ram
+    apt-get -y purge fs2ram
 #script self-destruct, deletes this script from disk. technically optional, as /tmp content gets dumped anyway on startup.
     rm /tmp/folder2ramhousekeeper
 exit 0
@@ -86,5 +93,162 @@ chmod +x ${HOUSEKEEPER}
 
 #calling it up as another process, so this script can quit and installation of whatever else can continue.
 bash ${HOUSEKEEPER}
+
+
+#now we need to put fs2ram to sleep safely if it is still online
+
+
+#checking if fs2ram is still there, if it isn't found the script ends here
+if [ ! -f /sbin/fs2ram ]; then
+exit 0;
+fi
+
+#################### UTILITY FUNCTIONS
+
+read_fs2ram_mount_points() {
+# this reads config file at a predetemined line and extracts mount point 
+# $line_number must come from outside
+# blank lines and commented lines are ignored, so line_number refers only to actual mount points
+
+line_number=$1 
+
+# remove blank and commented lines with sed, select only lines that have "keep_file_content" option,
+# get variable form outside in awk, and use it to print line at $line_number
+mount_point=$( sed '/^[[:space:]]*$/d' /etc/fs2ram/fs2ram.conf | sed '/^#/d' | sed -n '/keep_file_content/p' | awk -v line="$line_number" 'NR == line {print $2}' )
+
+# checking if mount point variable is empty, and if it is returning a keyword
+if [ "x$mount_point" != "x" ]; then 
+echo "$mount_point";
+else
+echo "no_more_mount_points";
+fi
+
+}
+
+########################## START OF SCRIPT ################################
+
+#moving files to temp folders so we can shut down fs2ram safely
+
+# initializing variables    
+line_number=1 
+
+echo "moving all tmpfs data to temp folders on system drive so we can get it back when fs2ram is powered down"
+
+######################CHECKING IF THERE ARE STILL MOUNT POINTS
+
+# calling another function (above) to fill the mount point at this line number
+mount_point=$(read_fs2ram_mount_points "$line_number")
+
+#########################################################
+
+############BEGINNING MAIN LOOP::::::::::::::::::::::::::::::::::::::
+
+until [ "$mount_point" = "no_more_mount_points" ] ;  do
+
+# calling another function (above) to fill DIR, a directory variable at this line number
+DIR=$(read_fs2ram_mount_points "$line_number")
+
+################FUNCTION PAYLOAD#############
+
+#this is the path of the temporary folders where we store things while powering down fs2ram
+DIRPERM="/var/folder2ram/temp$DIR"
+
+#making folder if not existing
+[ -d "$DIRPERM" ] || mkdir -p "$DIRPERM"
+
+#copy the contents of original folder in a temporary folder
+cp -rfp "$DIR" -T "$DIRPERM"
+
+####################################
+
+# increasing line number
+line_number=$((line_number+1))
+
+######################CHECKING IF THERE ARE STILL MOUNT POINTS
+
+# calling another function (above) to fill the mount point at this line number
+mount_point=$(read_fs2ram_mount_points "$line_number")
+
+#########################################################
+
+###########ENDING OF MAIN LOOP::::::::::::::::::::::::::
+done
+
+
+############DEACTIVATING FS2RAM
+
+# shuttins down fs2ram on all tmpfs
+fs2ram unmount -a -f
+
+#if it fails horribly it can be changed with yet another while cycle like the above, 
+#reading and and unmounting manually all mount points of fs2ram 
+#config file. I hope it won't be necessary.
+
+######################################
+
+############COPYING DATA BACK TO ORIGINAL FOLDERS:::::::::::::::
+
+echo "copying the data back to original folders in permanent storage"
+
+# initializing variables    
+line_number=1
+
+######################CHECKING IF THERE ARE STILL MOUNT POINTS
+
+# calling another function (above) to fill the mount point at this line number
+mount_point=$(read_fs2ram_mount_points "$line_number")
+
+#########################################################
+
+############BEGINNING MAIN LOOP::::::::::::::::::::::::::::::::::::::
+
+until [ "$mount_point" = "no_more_mount_points" ] ;  do
+
+# calling another function (above) to fill the mount point at this line number
+mount_point=$(read_fs2ram_mount_points "$line_number")
+
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+
+	# DIRPERM either does not exist or is empty?
+	# making it anyway.
+	# 
+	[ -d "$DIRPERM" ] || mkdir -p "$DIRPERM" || return 2
+
+	# If DIR does not exist?
+	[ -d "$DIR" ] || return 2
+
+	#checking if above went well
+	if [ $? -eq 0 ]; then
+		# move the data from temp folder to true folder in drive
+		if cp -rfp "$DIRPERM" -T "$DIR"; then
+			# Success!
+			echo "$DIR synced"
+		fi
+
+	fi
+	
+# increasing line number
+line_number=$((line_number+1))
+
+################CHECKING IF THERE ARE STILL MOUNT POINTS
+
+# calling another function (above) to fill the mount point at this line number
+mount_point=$(read_fs2ram_mount_points "$line_number")
+
+########################################################
+
+##########ENDING OF MAIN LOOP:::::::::::::::::::::::::::::
+done
+
+########################MAKING SURE FS2RAM STAYS DOWN
+# commenting out fs2ram config file so it will not come back
+sed -i "" "s/^\([^#]\)/#\1/g" /etc/fs2ram/fs2ram.conf
+
+#############SIGNALING READY TO HOUSEKEEPER
+touch /run/lock/fs2ramdisabled
+
 
 exit 0
